--liquibase formatted-sql
--changeset pavel:init

create table currencies
(
    code   varchar(3)  not null unique,
    symbol varchar(3)  not null,
    id     bigint generated by default as identity,
    name   varchar(50) not null,
    primary key (id)
);

create table users
(
    currency_id bigint,
    id          bigint generated by default as identity,
    username    varchar(255) unique,
    primary key (id)
);

create table add_purchase_states
(
    price       numeric(19, 2),
    amount      bigint,
    currency_id bigint references currencies(id),
    id          bigint generated by default as identity,
    user_id     bigint references users(id),
    step        varchar(50) not null check (step in ('WAITING_FOR_CURRENCY', 'WAITING_FOR_PRICE', 'WAITING_FOR_AMOUNT',
                                                     'WAITING_FOR_NAME')),
    name        varchar(255),
    primary key (id)
);

create table exchange_rates
(
    date date not null,
    id   bigint generated by default as identity,
    primary key (id)
);

create table currency_rate
(
    nominal          numeric(38, 2) not null,
    value            numeric(38, 2) not null,
    currency_id      bigint references currencies(id),
    exchange_rate_id bigint references exchange_rates(id),
    id               bigint generated by default as identity,
    primary key (id)
);

create table purchases
(
    price            numeric(38, 2) not null,
    amount           bigint         not null,
    currency_id      bigint references currencies(id),
    exchange_rate_id bigint references exchange_rates(id),
    id               bigint generated by default as identity,
    user_id          bigint references users(id),
    name             varchar(255)   not null,
    primary key (id)
);
